[[redirects]]
  from = "/"
  to = "/templates/Home"
  status = 200
[[redirects]]
  from = "/About"
  to = "/templates/About"
  status = 200
[[redirects]]
  from = "/Blog"
  to = "/templates/Blog"
  status = 200
[[redirects]]
  from = "/Cart"
  to = "/templates/Cart"
  status = 200
[[redirects]]
  from = "/Contact"
  to = "/templates/Contact"
  status = 200
[[redirects]]
  from = "/ProductDetail"
  to = "/templates/ProductDetail"
  status = 200
[[redirects]]
  from = "/ProductDetail.html"
  to = "/templates/ProductDetail"
  status = 200
[[redirects]]
  from = "/Shop"
  to = "/templates/Shop"
  status = 200